apiVersion: v1
kind: Namespace
metadata:
  name: kargo
  labels:
    app.kubernetes.io/name: kargo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo
  namespace: kargo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kargo
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- nonResourceURLs: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo
subjects:
- kind: ServiceAccount
  name: kargo
  namespace: kargo
