{{- if .Values.kargo.project.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.kargo.project.name }}
  labels:
    kargo.akuity.io/project: "true"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: {{ .Values.kargo.project.name }}
{{- end }}