apiVersion: v2
name: kargo
description: Kargo Helm chart for deployment
type: application
version: 1.0.0
appVersion: "v1.1.0"
dependencies:
  - name: kargo
    version: "1.8.4"
    repository: "oci://ghcr.io/akuity/kargo-charts"